name: "Codeception Tests"

on:
    schedule:
        -   cron: '0 3 * * 1,3,5'
    pull_request_target:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
    APP_ENV: test
    PIMCORE_TEST: 1
    PIMCORE_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/pimcore_test"

jobs:
    codeception-tests:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-codeception-tests.yaml@main
    with:
        APP_ENV: test
        PIMCORE_TEST: 1