name: "Codeception Tests"

on:
    schedule:
        -   cron: '0 3 * * 1,3,5'
    pull_request_target:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"

jobs:
    codeception-tests:
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-codeception-tests-public.yaml@main
        with:
            APP_ENV: test
            PIMCORE_TEST: 1